set nocompatible              " be iMproved, required
filetype off                  " required
syntax on

let mapleader=","
set showcmd
set path+=**
set wildmenu
set wildignore=+**/nodemodules/**
set tabstop=2
set shiftwidth=2
set list
set listchars=tab:→\ ,eol:↲,space:·
set so=20
set hlsearch
set noswapfile
set ignorecase
set smartcase
set number
set relativenumber
set incsearch
set smartindent
set autoindent
set mouse=a
set undodir=~/.vim/undodir
set undofile
set cursorcolumn
set cursorline


set colorcolumn=105
highlight ColorColumn ctermbg=grey guibg=lightgrey


"""""""""""""""""""""""""""
nnoremap <Left> :echo "No left for you!"<CR>
vnoremap <Left> :<C-u>echo "No left for you!"<CR>
"inoremap <Left> <C-o>:echo "No left for you!"<CR>

nnoremap <right> :echo "No right for you!"<CR>
vnoremap <right> :<C-u>echo "No right for you!"<CR>
"inoremap <right> <C-o>:echo "No right for you!"<CR>

nnoremap <up> :echo "No up for you!!!"<CR>
vnoremap <up> :<C-u>echo "No up for you!!!"<CR>
"inoremap <up> <C-o>:echo "No up for you!!!"<CR>

nnoremap <down> :echo "no down for you!!!"<cr>
vnoremap <down> :<c-u>echo "no down for you!!!"<cr>
"inoremap <down> <c-o>:echo "No down for you!!!"<cr>
""""""""""""""""""""""""""""""

call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'morhetz/gruvbox'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'lifepillar/pgsql.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'


call plug#end()

colorscheme gruvbox
set background=dark
map <C-p> :Files<CR>
map <C-n> :NERDTreeToggle<CR>
let g:netrw_browse_split=2
let g:netrw_winsize=25
let g:sql_type_default = 'pgsql'
let g:pgsql_pl = ['python']


let g:fzf_layout = {'window': {'width': 0.8, 'height': 0.8}}
let $FZF_DEFAUTS_OPS='--reverse'




nnoremap <leader>+ :vertical resize +5 
nnoremap <leader>+ :vertical resize -5 
